### PR TITLE
Upgrade to use latest dependencies

### PR DESCRIPTION
**Pull request by allimn**
*Issue #, if available:*

*Description of changes:*
Upgrade to use latest dependencies by running `npm update --save`,also fixed some compiling errors.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by allimn** [comment]
The test is failing because the latest released driver doesn't work with @smithy/smithy-client installed in the sample app. Same issue mentioned here https://github.com/awslabs/amazon-qldb-driver-nodejs/issues/534

**Comment by allimn** [comment]
Tested sample app with ready-to-release driver locally.
```
3c22fb0a946f:amazon-qldb-dmv-sample-nodejs allimn$ node dist/InsertDocument
(node:93446) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[LOG][Node.js QLDB Sample Code] Inserting multiple documents into the 'Person' table...
[LOG][Node.js QLDB Sample Code] Updating PersonIds for 'DriversLicense' and PrimaryOwner for 'VehicleRegistration'...
[LOG][Node.js QLDB Sample Code] Inserting multiple documents into the remaining tables...
```

**Comment by allimn** [comment]
@trstephen-amazon We need to bump the driver version to v3.1.0 after release and merge this cr

**Comment by trstephen-amazon** [comment]
Well this is tricky. 

```
npm ERR! peer ion-js@"^4.3.0" from amazon-qldb-driver-nodejs@3.0.1
```

This CI is going to pull the existing 3.0.1. We'll have to publish 3.1.0 then rerun CI.

**Review by trstephen-amazon — APPROVED** [review]
LGTM, pending successful CI after release of driver @ v3.1.0

**Pull request merged**
